name: Build API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore API/Service/Api.csproj
    - name: Build
      run: dotnet build API/Service/Api.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test API/Tests/Tests.csproj --no-restore --verbosity normal
    - name: When job has failed
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh issue create --title "The workflow ${{ github.workflow }} failed" --body "Job ${{ github.job }} failed on ${{ github.event_name }} to ${{ github.ref }}"
