name: API build and deploy

on:
  push:
    branches:
      - master
    paths:
      - 'API/**'
  pull_request:
    branches:
      - master
    paths:
      - 'API/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build API/Service/Api.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test API/Tests/Tests.csproj --no-restore --verbosity normal
    - name: The job has failed
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh issue create --title "The job has failed" --body "Build/deployment issue"
